apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  labels:
    app: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: llm
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
